import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='flex items-center justify-center text-3xl font-bold h-screen w-full'>
        Gm ☕️
      </h1>
    </div>
  )
}
